### PR TITLE
Fix to_dataframe call in Results to match function definition

### PR DESCRIPTION
**Pull request by appsworld**
The current definition for to_dataframe in the  Results class is to_dataframe(self), however the call to_dataframe(options=self.options) has an option argument, causing a TypeError

### CODE REVIEW

**Comment by mbnshtck** [comment]
can you please send me the error with full stack

**Comment by appsworld** [comment]
site-packages\Kqlmagic\results.py in to_dataframe(self)
    693         "Returns a Pandas DataFrame instance built from the result set."
    694         if self._dataframe is None:
--> 695             self._dataframe = self._queryResult.tables[self.fork_table_id].to_dataframe(options=self.options)
    696 
    697             # import pandas as pd

TypeError: to_dataframe() got an unexpected keyword argument 'options'

**Comment by mbnshtck** [comment]
I am not able to reproduce this error. I suggest that in your cloned version, add a print to the see the type of self.options before it is passed as parameter, it should be a dict. You can also before calling saved_result.to_dataframe() check the type of saved_result.options it should be dict, if it is not, check the type of it, when you set saved_result. Anyhow, the solution is not removing the options parameter.

**Comment by appsworld** [comment]
Yes, you're right, the bug was an artifact of a monkey patch to KqlTableResponse's to_dataframe method . 

The fix was to handle the instances where the time ranges fall out of the bounds fo pandas' max and min datetime, which triggers OutOfBoundsDatetime. E.g pd.to_datetime('02/18/2276 5:15:13 AM').  However the aforementioned is now fixed in the latest version of KqlMagic.


However while trying to reproduce what was happening I realized there was a pandas type checking error in in kql_magic_core, it is in the update to this PR. You can reproduce using the following: 

**You can recreate it with the following:**
```
%config Kqlmagic.auto_dataframe = True
%config Kqlmagic.short_errors = False
%reload_ext Kqlmagic

%kql  datatable (a: string)['a'] | take 1
```

**Stack Trace**
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-400e8bb1544e> in <module>
      1 get_ipython().run_line_magic('config', 'Kqlmagic.auto_dataframe = True')
      2 get_ipython().run_line_magic('config', 'Kqlmagic.short_errors = False')
----> 3 get_ipython().run_line_magic('kql', " datatable (a: string)['a'] | take 1")

/srv/conda/envs/notebook/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2305                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2306             with self.builtin_trap:
-> 2307                 result = fn(*args, **kwargs)
   2308             return result
   2309 

</srv/conda/envs/notebook/lib/python3.7/site-packages/decorator.py:decorator-gen-127> in execute(self, line, cell, local_ns, override_vars, override_options, override_query_properties, override_connection, override_result_set)

/srv/conda/envs/notebook/lib/python3.7/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

</srv/conda/envs/notebook/lib/python3.7/site-packages/decorator.py:decorator-gen-126> in execute(self, line, cell, local_ns, override_vars, override_options, override_query_properties, override_connection, override_result_set)

/srv/conda/envs/notebook/lib/python3.7/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/srv/conda/envs/notebook/lib/python3.7/site-packages/Kqlmagic/kql_magic.py in execute(self, line, cell, local_ns, override_vars, override_options, override_query_properties, override_connection, override_result_set)
    671             override_query_properties=override_query_properties,
    672             override_connection=override_connection,
--> 673             override_result_set=override_result_set)
    674 
    675         return result

/srv/conda/envs/notebook/lib/python3.7/site-packages/Kqlmagic/kql_magic_core.py in execute(self, line, cell, local_ns, override_vars, override_options, override_query_properties, override_connection, override_result_set)
    679 
    680                 if command is None or command == "submit":
--> 681                     result = self._execute_query(parsed, user_ns, result_set=override_result_set, override_vars=override_vars)
    682                     if type(result) == ResultSet:
    683                         # can't just return result as is, it fails when used with table package pandas_show_schema

/srv/conda/envs/notebook/lib/python3.7/site-packages/Kqlmagic/kql_magic_core.py in _execute_query(self, parsed, user_ns, result_set, override_vars)
   1103                 return None
   1104             else:
-> 1105                 raise e
   1106 
   1107 

/srv/conda/envs/notebook/lib/python3.7/site-packages/Kqlmagic/kql_magic_core.py in _execute_query(self, parsed, user_ns, result_set, override_vars)
   1088 
   1089 
-> 1090             if result == saved_result:
   1091                 result = saved_result.fork_result(fork_table_id)
   1092 

/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/core/generic.py in __nonzero__(self)
   1477     def __nonzero__(self):
   1478         raise ValueError(
-> 1479             f"The truth value of a {type(self).__name__} is ambiguous. "
   1480             "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
   1481         )

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`

**Comment by appsworld** [comment]
Appears to be fixed now upstream

**Pull request closed without merging**
