### PR TITLE
Add support for Azure CLI integrated authentication.

### PR DESCRIPTION
**Pull request by wpbrown**
In a scenario where you work in many customers tenants, and you may not be able get service principals, it can get cumbersome reauthenticating with device code when kernels are restarted. I considered adding a persistent token cache to Kqlmagic, but since the CLI already does that well, has nice management commands, and support for other auth methods (like managed identity), it was easier to just integrate with the CLI.

When `azcli` is specified in the connection string instead of `code`, a token will be retrieved or  refreshed by Azure CLI token cache. `subscription=` can be added to the connection string to select a login, like the `--subscription` argument of any `az` command.

This adds a new extra to the setup.py, `Kqlmagic[azcli]`, so the necessary libraries are only added if Azure CLI auth support is desired.

### CODE REVIEW

**Comment by danield137** [comment]
this is now available as part of the azure-kusto-python underlying sdk.
why reimplement it?

**Comment by wpbrown** [comment]
> this is now available as part of the azure-kusto-python underlying sdk.

Hi Daniel. I'm not the author of kqlmagic, but it looks like the authentication code was forked from that library long ago. This project doesn't use that library. Presumably some changes were needed to uniformly support Log Analytics, App Insights, and Kusto, not just Kusto.

> why reimplement it?

I commited [the change](https://github.com/wpbrown/jupyter-Kqlmagic/commit/1b3f2ef46179e94fa8de91b957391ce1764fe63b) a week before there was support in the library. Your code looks good though. It probably would make sense for Kqlmagic to use the Kusto library, and also to see how the authentication helper in the library could service the needs of Kqlmagic as well. Both helpers should probably be refactored to leverage the new [azure-identity SDK library](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/identity/azure-identity).

**Comment by mbnshtck** [comment]
Thank you for your contribution. Support for azcli_login was added as an option instead of connection string.

**Comment by wpbrown** [comment]
Test and confirmed new options work in post20. Thanks.

**Pull request closed without merging**
